
import type { RiyadhRegion } from '@/types';

export const RIYADH_REGIONS: { value: RiyadhRegion; labelAr: string; labelEn: string }[] = [
  { value: "North", labelAr: "شمال الرياض", labelEn: "North Riyadh" },
  { value: "East", labelAr: "شرق الرياض", labelEn: "East Riyadh" },
  { value: "West", labelAr: "غرب الرياض", labelEn: "West Riyadh" },
  { value: "South", labelAr: "جنوب الرياض", labelEn: "South Riyadh" },
  { value: "Central", labelAr: "وسط الرياض", labelEn: "Central Riyadh" },
  { value: "Other", labelAr: "أخرى/غير مصنف", labelEn: "Other/Unclassified" },
];

export const riyadhRegionArabicMap: Record<RiyadhRegion, string> =
  RIYADH_REGIONS.reduce((acc, curr) => {
    acc[curr.value] = curr.labelAr;
    return acc;
  }, {} as Record<RiyadhRegion, string>);


export const RIYADH_NEIGHBORHOODS_WITH_REGIONS: { value: string; labelAr: string; labelEn: string; region: RiyadhRegion }[] = [
  // شمال الرياض
  { value: "الربيع", labelAr: "الربيع", labelEn: "Ar Rabi", region: "North" },
  { value: "الندى", labelAr: "الندى", labelEn: "An Nada", region: "North" },
  { value: "الصحافة", labelAr: "الصحافة", labelEn: "As Sahafah", region: "North" },
  { value: "النرجس", labelAr: "النرجس", labelEn: "An Narjis", region: "North" },
  { value: "العارض", labelAr: "العارض", labelEn: "Al Arid", region: "North" },
  { value: "النفل", labelAr: "النفل", labelEn: "An Nafal", region: "North" },
  { value: "العقيق", labelAr: "العقيق", labelEn: "Al Aqiq", region: "North" },
  { value: "الوادي", labelAr: "الوادي", labelEn: "Al Wadi", region: "North" },
  { value: "الغدير", labelAr: "الغدير", labelEn: "Al Ghadir", region: "North" },
  { value: "الياسمين", labelAr: "الياسمين", labelEn: "Al Yasmin", region: "North" },
  { value: "الفلاح", labelAr: "الفلاح", labelEn: "Al Falah", region: "North" },
  { value: "بنبان", labelAr: "بنبان", labelEn: "Banban", region: "North" },
  { value: "القيروان", labelAr: "القيروان", labelEn: "Al Qayrawan", region: "North" },
  { value: "حطين", labelAr: "حطين", labelEn: "Hittin", region: "North" },
  { value: "الملقا", labelAr: "الملقا", labelEn: "Al Malqa", region: "North" },
  { value: "النخيل", labelAr: "النخيل", labelEn: "An Nakhil", region: "North" },
  { value: "المغرزات", labelAr: "المغرزات", labelEn: "Al Mugharrizat", region: "North" },
  { value: "المروج", labelAr: "المروج", labelEn: "Al Muruj", region: "North" },
  { value: "المصيف", labelAr: "المصيف", labelEn: "Al Masif", region: "North" },
  { value: "التعاون", labelAr: "التعاون", labelEn: "At Taawun", region: "North" },
  { value: "الإزدهار", labelAr: "الإزدهار", labelEn: "Al Izdihar", region: "North" },

  // شرق الرياض
  { value: "الروضة", labelAr: "الروضة", labelEn: "Ar Rawdah", region: "East" },
  { value: "الرمال", labelAr: "الرمال", labelEn: "Ar Rimal", region: "East" },
  { value: "المونسية", labelAr: "المونسية", labelEn: "Al Munisiyah", region: "East" },
  { value: "قرطبة", labelAr: "قرطبة", labelEn: "Qurtubah", region: "East" },
  { value: "الجنادرية", labelAr: "الجنادرية", labelEn: "Al Janadriyah", region: "East" },
  { value: "القادسية", labelAr: "القادسية", labelEn: "Al Qadisiyah", region: "East" },
  { value: "اليرموك", labelAr: "اليرموك", labelEn: "Al Yarmuk", region: "East" },
  { value: "غرناطة", labelAr: "غرناطة", labelEn: "Gharnatah", region: "East" },
  { value: "أشبيلية", labelAr: "أشبيلية", labelEn: "Ishbiliyah", region: "East" },
  { value: "الحمراء", labelAr: "الحمراء", labelEn: "Al Hamra", region: "East" },
  { value: "المعيزلية", labelAr: "المعيزلية", labelEn: "Al Maizilah", region: "East" },
  { value: "الخليج", labelAr: "الخليج", labelEn: "Al Khaleej", region: "East" },
  { value: "الملك فيصل", labelAr: "الملك فيصل", labelEn: "King Faisal", region: "East" },
  { value: "القدس", labelAr: "القدس", labelEn: "Al Quds", region: "East" },
  { value: "النهضة", labelAr: "النهضة", labelEn: "An Nahdah", region: "East" },
  { value: "الأندلس", labelAr: "الأندلس", labelEn: "Al Andalus", region: "East" },
  { value: "النسيم الشرقي", labelAr: "النسيم الشرقي", labelEn: "An Nasim Ash Sharqi", region: "East" },
  { value: "النسيم الغربي", labelAr: "النسيم الغربي", labelEn: "An Nasim Al Gharbi", region: "East" },
  { value: "السلام", labelAr: "السلام", labelEn: "As Salam", region: "East" },
  { value: "الريان", labelAr: "الريان", labelEn: "Ar Rayyan", region: "East" },
  { value: "الروابي", labelAr: "الروابي", labelEn: "Ar Rawabi", region: "East" },
  { value: "النظيم", labelAr: "النظيم", labelEn: "An Nadhim", region: "East" },
  { value: "المنار", labelAr: "المنار", labelEn: "Al Manar", region: "East" },
  { value: "الندوة", labelAr: "الندوة", labelEn: "An Nadwah", region: "East" },
  { value: "الفيحاء", labelAr: "الفيحاء", labelEn: "Al Fayha", region: "East" },
  { value: "الجزيرة", labelAr: "الجزيرة", labelEn: "Al Jazirah", region: "East" },
  { value: "السعادة", labelAr: "السعادة", labelEn: "As Saadah", region: "East" },
  { value: "هيت", labelAr: "هيت", labelEn: "Hit", region: "East" },
  { value: "البرية", labelAr: "البرية", labelEn: "Al Barriyah", region: "East" },
  { value: "المشاعل", labelAr: "المشاعل", labelEn: "Al Mashael", region: "East" },
  { value: "الربوة", labelAr: "الربوة", labelEn: "Ar Rabwah", region: "East" },

  // جنوب الرياض
  { value: "العزيزية", labelAr: "العزيزية", labelEn: "Al Aziziyah", region: "South" },
  { value: "الفيصلية (جنوب)", labelAr: "الفيصلية", labelEn: "Al Faisaliyah (South)", region: "South" },
  { value: "المروة", labelAr: "المروة", labelEn: "Al Marwah", region: "South" },
  { value: "الشفاء", labelAr: "الشفاء", labelEn: "Ash Shifa", region: "South" },
  { value: "الخالدية (جنوب)", labelAr: "الخالدية", labelEn: "Al Khalidiyah (South)", region: "South" },
  { value: "نمار", labelAr: "نمار", labelEn: "Namar", region: "South" },
  { value: "منفوحة", labelAr: "منفوحة", labelEn: "Manfuhah", region: "South" },
  { value: "الجبس", labelAr: "الجبس", labelEn: "Al Jibs", region: "South" },
  { value: "المنصورة", labelAr: "المنصورة", labelEn: "Al Mansurah", region: "South" },
  { value: "الدار البيضاء", labelAr: "الدار البيضاء", labelEn: "Ad Dar Al Baida", region: "South" },
  { value: "غبيراء", labelAr: "غبيراء", labelEn: "Ghubairah", region: "South" },
  { value: "الشعلان", labelAr: "الشعلان", labelEn: "Ash Shalan", region: "South" },
  { value: "بدر", labelAr: "بدر", labelEn: "Badr", region: "South" },
  { value: "اليمامة", labelAr: "اليمامة", labelEn: "Al Yamamah", region: "South" },
  { value: "الدريهمية", labelAr: "الدريهمية", labelEn: "Ad Durayhimiyah", region: "South" },
  { value: "بن تركي", labelAr: "بن تركي", labelEn: "Ibn Turki", region: "South" },
  { value: "الحاير", labelAr: "الحاير", labelEn: "Al Hair", region: "South" },
  { value: "المصانع", labelAr: "المصانع", labelEn: "Al Masani", region: "South" },
  { value: "الفواز", labelAr: "الفواز", labelEn: "Al Fawaz", region: "South" },
  { value: "أحد", labelAr: "أحد", labelEn: "Uhud", region: "South" },
  { value: "عكاظ", labelAr: "عكاظ", labelEn: "Okaz", region: "South" },
  { value: "المنصورية", labelAr: "المنصورية", labelEn: "Al Mansuriyah", region: "South" },
  { value: "عريض", labelAr: "عريض", labelEn: "Uraydh", region: "South" },
  { value: "العماجية", labelAr: "العماجية", labelEn: "Al Ammajiyah", region: "South" }, // Corrected from Al Ammariyah
  { value: "طيبة", labelAr: "طيبة", labelEn: "Tibah", region: "South" },
  { value: "المصفاة", labelAr: "المصفاة", labelEn: "Al Musaffah", region: "South" },
  { value: "الغنامية", labelAr: "الغنامية", labelEn: "Al Ghannamiyah", region: "South" },
  { value: "سلام", labelAr: "سلام", labelEn: "Salam", region: "South" },
  { value: "جبرة", labelAr: "جبرة", labelEn: "Jabrah", region: "South" },
  { value: "عتيقة", labelAr: "عتيقة", labelEn: "Atiqah", region: "South" },
  { value: "البطيحا", labelAr: "البطيحا", labelEn: "Al Batha", region: "South" },
  { value: "العود", labelAr: "العود", labelEn: "Al Oud", region: "South" },
  { value: "المرقب", labelAr: "المرقب", labelEn: "Al Marqab", region: "South" },
  { value: "منفوحة الجديدة", labelAr: "منفوحة الجديدة", labelEn: "Manfuhah Al Jadidah", region: "South" },
  { value: "الدوبية", labelAr: "الدوبية", labelEn: "Ad Dubiyah", region: "South" },
  { value: "القرى", labelAr: "القرى", labelEn: "Al Quraya", region: "South" },
  { value: "الصناعية", labelAr: "الصناعية", labelEn: "As Sinaiyah", region: "South" },
  { value: "الوسيطاء", labelAr: "الوسيطاء", labelEn: "Al Wusayta", region: "South" },
  { value: "معكال", labelAr: "معكال", labelEn: "Mikal", region: "South" },
  { value: "الديرة (جنوب)", labelAr: "الديرة", labelEn: "Ad Dirah (South)", region: "South" },

  // غرب الرياض
  { value: "السويدي", labelAr: "السويدي", labelEn: "As Suwaidi", region: "West" },
  { value: "الدرعية", labelAr: "الدرعية", labelEn: "Ad Diriyah", region: "West" },
  { value: "لبن (ظهرة لبن)", labelAr: "لبن (ظهرة لبن)", labelEn: "Laban (Dhahrat Laban)", region: "West" },
  { value: "البديعة", labelAr: "البديعة", labelEn: "Al Badi'ah", region: "West" },
  { value: "ظهرة البديعة", labelAr: "ظهرة البديعة", labelEn: "Dhahrat Al Badi'ah", region: "West" },
  { value: "شبرا", labelAr: "شبرا", labelEn: "Shubra", region: "West" },
  { value: "العريجاء", labelAr: "العريجاء", labelEn: "Al Uraija", region: "West" },
  { value: "جامعة الملك سعود", labelAr: "جامعة الملك سعود", labelEn: "King Saud University", region: "West" },
  { value: "السفارات", labelAr: "السفارات", labelEn: "As Safarat (Diplomatic Quarter)", region: "West" },
  { value: "المهدية", labelAr: "المهدية", labelEn: "Al Mahdiyah", region: "West" },
  { value: "عرقة", labelAr: "عرقة", labelEn: "Irqah", region: "West" },
  { value: "الخزامى", labelAr: "الخزامى", labelEn: "Al Khuzama", region: "West" },
  { value: "الرفيعة", labelAr: "الرفيعة", labelEn: "Ar Rafiah", region: "West" },
  { value: "الهدا", labelAr: "الهدا", labelEn: "Al Hada", region: "West" },
  { value: "الشرقية (غرب)", labelAr: "الشرقية", labelEn: "Ash Sharqiyah (West)", region: "West" },
  { value: "الناصرية (غرب)", labelAr: "الناصرية", labelEn: "An Nasiriyah (West)", region: "West" },
  { value: "صياح", labelAr: "صياح", labelEn: "Sayyah", region: "West" },
  { value: "الوشام", labelAr: "الوشام", labelEn: "Al Washam", region: "West" },
  { value: "النموذجية", labelAr: "النموذجية", labelEn: "An Namudhajiyah", region: "West" },
  { value: "المؤتمرات", labelAr: "المؤتمرات", labelEn: "Al Mutamarat", region: "West" },
  { value: "أم سليم", labelAr: "أم سليم", labelEn: "Umm Salim", region: "West" },
  { value: "الشميسي", labelAr: "الشميسي", labelEn: "Ash Shumaysi", region: "West" },
  { value: "الجرادية", labelAr: "الجرادية", labelEn: "Al Jaradiyah", region: "West" },
  { value: "الفاخرية (غرب)", labelAr: "الفاخرية", labelEn: "Al Fakhiriyah (West)", region: "West" },
  { value: "عليشة", labelAr: "عليشة", labelEn: "Ulaishah", region: "West" },
  { value: "العريجاء الوسطى", labelAr: "العريجاء الوسطى", labelEn: "Al Uraija Al Wusta", region: "West" },
  { value: "العريجاء الغربية", labelAr: "العريجاء الغربية", labelEn: "Al Uraija Al Gharbiyah", region: "West" },
  { value: "سلطانة", labelAr: "سلطانة", labelEn: "Sultanah", region: "West" },
  { value: "الزهرة (غرب)", labelAr: "الزهرة", labelEn: "Az Zahrah (West)", region: "West" },
  { value: "ظهرة نمار", labelAr: "ظهرة نمار", labelEn: "Dhahrat Namar", region: "West" },
  { value: "ديراب", labelAr: "ديراب", labelEn: "Dirab", region: "West" },
  { value: "الحزم", labelAr: "الحزم", labelEn: "Al Hazm", region: "West" },
  { value: "أم الحمام الشرقي", labelAr: "أم الحمام الشرقي", labelEn: "Umm Al Hamam Ash Sharqi", region: "West" },
  { value: "أم الحمام الغربي", labelAr: "أم الحمام الغربي", labelEn: "Umm Al Hamam Al Gharbi", region: "West" },
  { value: "الرائد", labelAr: "الرائد", labelEn: "Ar Raid", region: "West" },

  // وسط الرياض
  { value: "العليا", labelAr: "العليا", labelEn: "Al Olaya", region: "Central" },
  { value: "السليمانية", labelAr: "السليمانية", labelEn: "As Sulimaniyah", region: "Central" },
  { value: "الملك عبد العزيز", labelAr: "الملك عبد العزيز", labelEn: "King Abdulaziz", region: "Central" },
  { value: "الملك عبد الله", labelAr: "الملك عبد الله", labelEn: "King Abdullah", region: "Central" },
  { value: "الورود", labelAr: "الورود", labelEn: "Al Wurud", region: "Central" },
  { value: "صلاح الدين", labelAr: "صلاح الدين", labelEn: "Salah Ad Din", region: "Central" },
  { value: "الملك فهد", labelAr: "الملك فهد", labelEn: "King Fahd", region: "Central" },
  { value: "المرسلات", labelAr: "المرسلات", labelEn: "Al Mursalat", region: "Central" },
  { value: "النزهة", labelAr: "النزهة", labelEn: "An Nuzhah", region: "Central" },
  { value: "جرير", labelAr: "جرير", labelEn: "Jarir", region: "Central" },
  { value: "الزهراء (وسط)", labelAr: "الزهراء", labelEn: "Az Zahra (Central)", region: "Central" },
  { value: "الصفا", labelAr: "الصفا", labelEn: "As Safa", region: "Central" },
  { value: "الضباط", labelAr: "الضباط", labelEn: "Ad Dubbat", region: "Central" },
  { value: "الملز", labelAr: "الملز", labelEn: "Al Malaz", region: "Central" },
  { value: "الوزارات", labelAr: "الوزارات", labelEn: "Al Wizarat", region: "Central" },
  { value: "الفاروق", labelAr: "الفاروق", labelEn: "Al Faruq", region: "Central" },
  { value: "العمل", labelAr: "العمل", labelEn: "Al Amal", region: "Central" },
  { value: "ثليم", labelAr: "ثليم", labelEn: "Thulaim", region: "Central" },
  { value: "المربع", labelAr: "المربع", labelEn: "Al Murabba", region: "Central" },
  { value: "الفوطة", labelAr: "الفوطة", labelEn: "Al Futah", region: "Central" },
  { value: "المعذر", labelAr: "المعذر", labelEn: "Al Ma'athar", region: "Central" },
  { value: "المحمدية", labelAr: "المحمدية", labelEn: "Al Muhammadiyah", region: "Central" },
  { value: "الرحمانية", labelAr: "الرحمانية", labelEn: "Ar Rahmaniyah", region: "Central" },
  // Add more neighborhoods here as needed with their correct region
].sort((a, b) => a.labelAr.localeCompare(b.labelAr, 'ar'));


export const ALL_RIYADH_NEIGHBORHOODS_FOR_SELECT = RIYADH_NEIGHBORHOODS_WITH_REGIONS.map(n => ({value: n.value, labelAr: n.labelAr, labelEn: n.labelEn})).sort((a,b) => a.labelAr.localeCompare(b.labelAr, 'ar'));

    